name: Get Issue Data
on:
  issues:
    types:
      - opened
      - edited

jobs:
  fetch_issue_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create JSON with issue data
        run: |
          mkdir -p issues
          FILE="issues/issue.json"
          echo "FILE=$FILE" >> $GITHUB_ENV
          gh issue view $ISSUE_NUMBER --json title,body,labels,assignees,createdAt,updatedAt > issue_data.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Display issue data
        run: |
          cat issue_data.json

      - name: Commit to separate branch
        run: |
          BRANCH="issue-${{ github.event.issue.number }}"
          git switch main
          git pull origin main
          git switch -C "$BRANCH"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILE
          git commit -m "Adding issue data #${{ github.event.issue.number }}" || echo "Nothing to commit"
          git push origin "$BRANCH" --force
