name: Get Issue Data
on:
  issues:
    types:
      - opened
      - edited

jobs:
  fetch_issue_data:
    runs-on: ubuntu-latest
    steps:
      - name: Salvar dados da issue
        run: |
          echo "Título: ${{ github.event.issue.title }}" > issue_data.txt
          echo "" >> issue_data.txt
          echo "Corpo:" >> issue_data.txt
          echo "${{ github.event.issue.body }}" >> issue_data.txt
          echo "" >> issue_data.txt
          echo "Labels:" >> issue_data.txt
          for label in ${{ toJson(github.event.issue.labels) }}; do
            echo "- $label" >> issue_data.txt
          done
          
      - name: Exibir conteúdo
        run: cat issue_data.txt
      - name: Commitar e fazer push
             git config user.name "GitHub Actions"
          git config user.email "jlprcarvalho@gmail.com"
          git add issue_data.txt
          git commit -m "Adicionando novo arquivo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}