name: Get Issue Body
on:
  issues:
    types:
      - opened
      - edited
jobs:
  fetch_issue_body:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch issue body
        run: |
          issue_body=$(gh api repos/$OWNER/$REPO/issues/$ISSUE_NUMBER --jq '.body')
          echo "$issue_body" > issue_body.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}