name: Get Issue Data
on:
  issues:
    types:
      - opened
      - edited

jobs:
  fetch_issue_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Criar arquivo com dados da issue
        run: |
          mkdir -p issues
          FILE="issues/issue-${{ github.event.issue.number }}.txt"

          echo "Título: ${{ github.event.issue.title }}" > $FILE
          echo "" >> $FILE
          echo "Corpo:" >> $FILE
          echo "${{ github.event.issue.body }}" >> $FILE
          echo "" >> $FILE
          echo "Labels:" >> $FILE
          echo "${{ toJson(github.event.issue.labels) }}" >> $FILE

      - name: Commitar em branch separada
        run: |
          BRANCH="issue-${{ github.event.issue.number }}"

          # Atualizar main local
          git switch main
          git pull origin main

          # Criar ou trocar para a branch
          git switch -C "$BRANCH"

          # Configurar autor do commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Adicionar e commitar
          git add issues/issue-${{ github.event.issue.number }}.txt
          git commit -m "Adicionando dados da issue #${{ github.event.issue.number }}" || echo "Nada para commitar"

          # Push da branch
          git push origin "$BRANCH" --force
